name = "debug-import-lean-macos"
version = "0.1.0"
defaultTargets = ["ImportMathlib", "ImportMathlibModule"]

[[lean_lib]]
name = "ImportMathlib"

[[lean_lib]]
name = "ImportMathlibModule"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4-nightly-testing.git"
rev = "nightly-testing"
